spring:
  ai:
    azure:
      openai:
        api-key: "ACTUAL_API_KEY"
        endpoint: "ACTUAL_ENDPOINT"
        embedding:
          options:
            deployment-name: "shinyay-gpt"
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
