# https://oai.azure.com/portal/

export SPRING_AI_AZURE_OPENAI_API_KEY="NEW_API_KEY"
export SPRING_AI_AZURE_OPENAI_ENDPOINT="NEW_ENDPOINT"
export SPRING_AI_AZURE_OPENAI_CHAT_OPTIONS_DEPLOYMENT_NAME="NEW_DEPLOYMENT_NAME"
