# https://oai.azure.com/portal/

# export SPRING_AI_AZURE_OPENAI_API_KEY="YOUR_ACTUAL_API_KEY_HERE"
# export SPRING_AI_AZURE_OPENAI_ENDPOINT="YOUR_ACTUAL_ENDPOINT_HERE"
# export SPRING_AI_AZURE_OPENAI_MODEL="YOUR_ACTUAL_MODEL_NAME_HERE"

export SPRING_AI_AZURE_OPENAI_API_KEY=""
export SPRING_AI_AZURE_OPENAI_ENDPOINT=""
export SPRING_AI_AZURE_OPENAI_CHAT_OPTIONS_DEPLOYMENT_NAME="shinyay-gpt"
