# https://oai.azure.com/portal/

export SPRING_AI_AZURE_OPENAI_API_KEY="YOUR_ACTUAL_API_KEY_HERE"
export SPRING_AI_AZURE_OPENAI_ENDPOINT="YOUR_ACTUAL_ENDPOINT_HERE"
export SPRING_AI_AZURE_OPENAI_MODEL="YOUR_ACTUAL_MODEL_NAME_HERE"
